### ISSUE TITLE
implement lower level babashka.pods/invoke function to support callbacks

### ISSUE THREAD

**Issue by borkdude** [babashka/babashka.pods#6]
See #5. This is a way to let pod functions take callbacks. This allows getting rid of core.async in pods.

**Comment by borkdude** [comment]
``` clojure
user=> (require '[babashka.pods :as pods])
nil
user=> (pods/load-pod "pod-babashka-filewatcher")
nil
user=> (babashka.pods.impl/invoke-public "pod.babashka.filewatcher" 'pod.babashka.filewatcher/watch ["/tmp"] {:on-success prn})
nil
user=> {:value {:path "/private/tmp/foobar4.txt", :type "create"}, :done false}
```

**Comment by borkdude** [comment]
@lispyclouds @retrogradeorbit 

This is a proposal to make core.async optional by introducing a lower level `babashka.pods/invoke` function that the pod can use in a wrapper interface using client side code. The pod can then decide how and where the callbacks should be placed in pod functions.
 
Any feedback on the above?

**Comment by borkdude** [comment]
Example using [filewatcher](https://github.com/babashka/pod-babashka-filewatcher), branch [callbacks](https://github.com/babashka/pod-babashka-filewatcher/tree/callbacks):

``` clojure
$ clj
Clojure 1.10.1
user=> (require '[babashka.pods :as pods])
nil
user=> (pods/load-pod "pod-babashka-filewatcher")
nil
user=> (require '[pod.babashka.filewatcher :as fw])
nil
user=> (fw/watch "/tmp" (fn [result] (prn "result" result)))
nil
user=> (spit "/tmp/foobar123.txt" "foo")
nil
user=> "result" {:path "/private/tmp/foobar123.txt", :type "create"}
```

**Comment by retrogradeorbit** [comment]
I like this. Nice and simple. What is the string first arg to `invoke` for?

**Comment by borkdude** [comment]
@retrogradeorbit That is used to lookup the pod by id. `invoke` needs to know which pod it's going to invoke. Although it could maybe just infer that from the var it's going to invoke...

**Comment by borkdude** [comment]
The benefit of using an explicit pod identifier (that's either explicitly communicated by the pod, or inferred from the name first namespace it defines) is that we can also use it:

- as a return value from `load-pod`
- as  an argument to `unload-pod` to shut the pod down

Instead of working directly with pod objects with contain a lot of implementation details that we do not want to expose (yet), we just work with a pod identifier which you can pass to various pod operations.

**Comment by retrogradeorbit** [comment]
Yep. sounds fine. Just curious why it was there.

**Comment by borkdude** [comment]
@retrogradeorbit @lispyclouds "Official" docs:

https://github.com/babashka/babashka.pods/tree/low-level-invoke#async

**Comment by jeroenvandijk** [comment]
I think callbacks are a great idea to make it independent of `core.async`. It would be great though if `pod/invoke` kept a synchronous signature. This is useful for `in-process` environments such as javascript that cannot wait for a thread. This would prevent making code in these environments full of callbacks (in the current code this is done [here](https://github.com/babashka/babashka.pods/blob/8f16139ab6e73a91aeb5fe97b398b30670e3fc9b/src/babashka/pods/impl.clj#L113-L117)). This would not work for all type of Pods (e.g. file watcher or a server side event listener. These pods would have to complain when the synchronous api is called.

It would also be great if JVM specifics were nicely hidden, e.g.
https://github.com/babashka/babashka.pods/blob/8f16139ab6e73a91aeb5fe97b398b30670e3fc9b/src/babashka/pods/impl.clj#L123-L132 
Or
https://github.com/babashka/babashka.pods/blob/8f16139ab6e73a91aeb5fe97b398b30670e3fc9b/src/babashka/pods/impl.clj#L145-L151

And would be nice if we could swap the serialization functions of bencode with transcript for instance https://github.com/babashka/babashka.pods/blob/8f16139ab6e73a91aeb5fe97b398b30670e3fc9b/src/babashka/pods/impl.clj#L15-L24

**Comment by borkdude** [comment]
> It would be great though if pod/invoke kept a synchronous signature.

`pod/invoke` already works works synchronously when it's not provided with callbacks.

> It would also be great if JVM specifics were nicely hidden

the entire `impl` namespace is *impl*ementation detail, so it's already hidden.

**Comment by borkdude** [comment]
> It would be great though if pod/invoke kept a synchronous signature.

`pod/invoke` already works works synchronously when it's not provided with callbacks.

But when calling pod vars synchronously, you're not even going to need the lower level interface in the first place.

> It would also be great if JVM specifics were nicely hidden

the entire `impl` namespace is *impl*ementation detail, so it's already hidden.

> And would be nice if we could swap the serialization functions of bencode with transcript for instance

bencode is chosen as the base message format, same as in the nREPL protocol. JSON/EDN are choices on top of that to encode payloads. Transit could be added as a choice. You can read about the why of this here: https://github.com/borkdude/babashka/blob/master/doc/pods.md

**Comment by jeroenvandijk** [comment]
> But when calling pod vars synchronously, you're not even going to need the lower level interface in the first place

This is not true for advanced compilation; the reason we cannot combine Sci javascript libraries.
